grpc:
  port: 8081

http:
  port: 9091

logging:
  level: debug
  format: console

swagger-ui:
  path: /app/swagger-ui
  enabled: true

database:
  host: db
  port: 5432
  user: user
  password: pass
  database: notificator
  options: sslmode=disable

secrets:
  ids:
    web-push-api: e6q2fjskiam5gqb224ss
    x-api-key: e6qrit49b41qnhsrfa8u
    token: e6qo9u8d7n70ciqo8omk