http:
  port: 80

grpc:
  port: 5051

logging:
  level: info
  format: json

database:
  host: rc1a-1ns3p57pcpp20u6s.mdb.yandexcloud.net
  port: 6432
  database: notificator
  options: sslmode=verify-full&target_session_attrs=read-write&sslrootcert=/root/.postgresql/root.crt

secrets:
  ids:
    db: e6qoug3fau0c6bhsj20i
    token: e6qo9u8d7n70ciqo8omk