# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0fuser_service.v1\"n\n&SetUserVerificationStatusByIDV1Request\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x33\n\x06status\x18\x02 \x01(\x0e\x32#.user_service.v1.VerificationStatus\":\n\'SetUserVerificationStatusByIDV1Response\x12\x0f\n\x07success\x18\x01 \x01(\x08*A\n\x12VerificationStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04PASS\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02\x12\n\n\x06MANUAL\x10\x03\x32\xa4\x01\n\x0bUserService\x12\x94\x01\n\x1fSetUserVerificationStatusByIDV1\x12\x37.user_service.v1.SetUserVerificationStatusByIDV1Request\x1a\x38.user_service.v1.SetUserVerificationStatusByIDV1Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFICATIONSTATUS']._serialized_start=211
  _globals['_VERIFICATIONSTATUS']._serialized_end=276
  _globals['_SETUSERVERIFICATIONSTATUSBYIDV1REQUEST']._serialized_start=39
  _globals['_SETUSERVERIFICATIONSTATUSBYIDV1REQUEST']._serialized_end=149
  _globals['_SETUSERVERIFICATIONSTATUSBYIDV1RESPONSE']._serialized_start=151
  _globals['_SETUSERVERIFICATIONSTATUSBYIDV1RESPONSE']._serialized_end=209
  _globals['_USERSERVICE']._serialized_start=279
  _globals['_USERSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
