services:
  db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  s3:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  matcher:
    build:
      context: .
      dockerfile: matcher/dev.Dockerfile
    environment:
      APP_ENV: dev
      CONFIGS_PATH: /app/configs
    ports:
      - "7001:7001"
      - "7002:7002"
    depends_on:
      db:
        condition: service_healthy

  auth:
    build:
      context: .
      dockerfile: auth/dev.Dockerfile
    environment:
      APP_ENV: dev
      CONFIGS_PATH: /app/configs
    volumes:
      - ./auth/swagger/api:/app/swagger-ui/api
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy