services:
  db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  auth:
    build:
      context: ./auth
      dockerfile: testing.Dockerfile
    environment:
      APP_ENV: tests
      CONFIGS_PATH: /app/configs
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy

  migrate:
    image: migrate/migrate
    entrypoint: ["migrate", "-source", "file://migrations", "-database", "postgres://user:pass@db:5432/auth?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy