grpc:
  port: 7002

http:
  port: 7001

logging:
  level: debug
  format: console

swagger-ui:
  path: /app/swagger-ui
  enabled: true

database:
  host: db
  port: 5432
  user: user
  password: pass
  database: matcher
  options: sslmode=disable
