grpc:
  port: 7002

http:
  port: 7001

logging:
  level: debug
  format: console

swagger-ui:
  path: /app/swagger-ui
  enabled: true

database:
  host: db
  port: 5432
  user: user
  password: pass
  database: matcher
  options: sslmode=disable

s3:
  endpoint: s3:9000
  accessKey: minio
  secretKey: minio123
  bucket: profile-photos

secrets:
  ids:
    sqs: e6q11avjgsnllkss9nqr
    x-api-key: e6qrit49b41qnhsrfa8u
