http:
  port: 80

grpc:
  port: 50051

logging:
  level: info
  format: json

database:
  host: rc1a-1ns3p57pcpp20u6s.mdb.yandexcloud.net
  port: 6432
  database: matcher
  options: sslmode=verify-full&target_session_attrs=read-write&sslrootcert=/root/.postgresql/root.crt

secrets:
  ids:
    db: e6qoug3fau0c6bhsj20i
    token: e6qo9u8d7n70ciqo8omk
    aws: e6q98r233qa96qq01il3

s3:
  endpoint: storage.yandexcloud.net
  bucket: testing-couply-profile-photos
  secure: true