name: 'Upload to s3'
description: 'Upload build to s3'

inputs:
  artifact-name:
    description: Name of the artifact
    required: true
  artifact-path:
    description: Path to the artifact
    required: true
  s3-bucket:
    description: S3 bucket name
    required: true
  yc-service-key:
    description: Yandex Cloud service key
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    - name: Set release version
      shell: bash
      run: echo "RELEASE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Setup MinIO Client
      shell: bash
      run: |
        curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        ./mc --version

    - name: Setup yc
      shell: bash
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yc -n
        echo '${{ inputs.yc-service-key }}' > sa-key.json
        /opt/yc/bin/yc config set folder-id b1ggapscf0p06cohndtt
        /opt/yc/bin/yc config set service-account-key sa-key.json

    - name: Configure MinIO Client
      shell: bash
      run: |
        ACCESS_KEY=$(/opt/yc/bin/yc lockbox payload get --name aws-testing --key aws-access-key)
        SECRET_KEY=$(/opt/yc/bin/yc lockbox payload get --name aws-testing --key aws-secret-key)
        ./mc alias set ycs3 https://storage.yandexcloud.net $ACCESS_KEY $SECRET_KEY

    - name: Deploy to MinIO
      shell: bash
      run: |
        ./mc cp -r ./${{ inputs.artifact-path }}/* ycs3/${{ inputs.s3-bucket }}/