grpc:
  port: 7004

http:
  port: 7003

logging:
  level: debug
  format: console

swagger-ui:
  path: /app/swagger-ui
  enabled: true

database:
  host: db
  port: 5432
  user: user
  password: pass
  database: blocker
  options: sslmode=disable

secrets:
  ids:
    telegram: e6qmaouf40ikg9lc7amg

matcher:
  address:  "matcher:7002"