grpc:
  port: 7004

http:
  port: 7003

logging:
  level: debug
  format: console

swagger-ui:
  path: /app/swagger-ui
  enabled: true

secrets:
  ids:
    telegram: e6qmaouf40ikg9lc7amg

user_service:
  address:  "matcher:7002"