// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: search-service/v1/search_service.proto

package search_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchingService_CreateFilterV1_FullMethodName = "/backend.SearchingService/CreateFilterV1"
)

// SearchingServiceClient is the client API for SearchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchingServiceClient interface {
	CreateFilterV1(ctx context.Context, in *CreateFilterV1Request, opts ...grpc.CallOption) (*CreateFilterV1Response, error)
}

type searchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchingServiceClient(cc grpc.ClientConnInterface) SearchingServiceClient {
	return &searchingServiceClient{cc}
}

func (c *searchingServiceClient) CreateFilterV1(ctx context.Context, in *CreateFilterV1Request, opts ...grpc.CallOption) (*CreateFilterV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFilterV1Response)
	err := c.cc.Invoke(ctx, SearchingService_CreateFilterV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchingServiceServer is the server API for SearchingService service.
// All implementations must embed UnimplementedSearchingServiceServer
// for forward compatibility.
type SearchingServiceServer interface {
	CreateFilterV1(context.Context, *CreateFilterV1Request) (*CreateFilterV1Response, error)
	mustEmbedUnimplementedSearchingServiceServer()
}

// UnimplementedSearchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchingServiceServer struct{}

func (UnimplementedSearchingServiceServer) CreateFilterV1(context.Context, *CreateFilterV1Request) (*CreateFilterV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFilterV1 not implemented")
}
func (UnimplementedSearchingServiceServer) mustEmbedUnimplementedSearchingServiceServer() {}
func (UnimplementedSearchingServiceServer) testEmbeddedByValue()                          {}

// UnsafeSearchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchingServiceServer will
// result in compilation errors.
type UnsafeSearchingServiceServer interface {
	mustEmbedUnimplementedSearchingServiceServer()
}

func RegisterSearchingServiceServer(s grpc.ServiceRegistrar, srv SearchingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchingService_ServiceDesc, srv)
}

func _SearchingService_CreateFilterV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFilterV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchingServiceServer).CreateFilterV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchingService_CreateFilterV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchingServiceServer).CreateFilterV1(ctx, req.(*CreateFilterV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchingService_ServiceDesc is the grpc.ServiceDesc for SearchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.SearchingService",
	HandlerType: (*SearchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFilterV1",
			Handler:    _SearchingService_CreateFilterV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search-service/v1/search_service.proto",
}
