name: 'Codegen'
description: 'Generate code for service'

runs:
  using: "composite"
  steps:
    - name: Cache tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          /tmp/buf-cache
        key: ${{ runner.os }}-tools-${{ hashFiles('backend/go.mod', 'backend/go.sum', 'backend/buf.yaml') }}
        restore-keys: |
          ${{ runner.os }}-tools-

    - name: Set up Go
      uses: actions/setup-go@v5.1.0
      with:
        go-version-file: backend/go.mod
        cache: false

    - name: Setup Buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Install protoc generators
      shell: bash
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
        go install github.com/envoyproxy/protoc-gen-validate/cmd/protoc-gen-validate-go@latest

    - name: Install mockgen
      shell: bash
      run: |
        go install go.uber.org/mock/mockgen@latest

    - name: Run go generate
      shell: bash
      working-directory: backend
      run: go generate ./...
