grpc:
  port: 8080

http:
  port: 9090

logging:
  level: debug
  format: console

swagger-ui:
  path: /app/swagger-ui
  enabled: true

database:
  host: db
  port: 5432
  user: user
  password: pass
  database: auth
  options: sslmode=disable

phone-confirmation:
  length: 6
  expirationTime: 1m

jwt:
  tokenLifetime: 30m

secrets:
  ids:
    smsru: e6qeb7ef6o0sgb12n3r0

smsru:
  test: true