linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gocognit

linters-settings:
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 20

run:
  timeout: 5m
  go: '1.23'