name: Auth Service Release Flow
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/backend-service-release.yml
    with:
      service_name: auth
      db_name: auth
      instance_group_name: auth-testing
    secrets: inherit
