name: Auth Service CI/CD

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'backend/auth/**'
      - 'backend/common/**'
      - '.github/workflows/auth-backend.yml'
      - '.github/workflows/backend-service-ci.yml'
      - '.github/actions/codegen/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/backend-service-ci.yml
    with:
      service_name: auth
    secrets: inherit

  success:
    name: CI success
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "All required checks passed!"