name: Backend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Run linter
        run: golangci-lint run ./...

      - name: Run tests
        run: go test ./... -v

      - name: Generate coverage report
        run: go test ./... -coverprofile=coverage.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

      - name: Build
        run: go build -o app ./...
