name: Auth Service CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - 'backend/auth/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'backend/auth/**'

jobs:
  build_and_checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/auth
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.23.5'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Install buf
        run: go install github.com/bufbuild/buf/cmd/buf@latest

      - name: Pull common proto files
        working-directory: backend
        run: buf export buf.build/googleapis/googleapis --output common/proto/

      - name: Run go generate
        run: go generate ./...

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Unit-Tests
        run: go test -v ./...
