name: Notificator Service CI/CD

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'backend/notificator/**'
      - 'backend/auth/pkg/**'
      - 'backend/common/**'
      - '.github/workflows/notificator-backend.yml'
      - '.github/workflows/backend-service-ci.yml'
      - '.github/actions/codegen/**'

# Cancel any in-progress job or run for the same branch/PR to save resources
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/backend-service-ci.yml
    with:
      service_name: notificator
    secrets: inherit

  success:
    name: CI success
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "All required checks passed!"