name: Payments Service Release Flow
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/backend-service-release.yml
    with:
      service_name: payments
      db_name: payments
      instance_group_name: payments-testing
    secrets: inherit
