name: Stub ci success

on:
  pull_request:
    branches: ["main"]
    paths:
      - './**'

jobs:
  ci-success:
    name: CI success
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Stub required check passed!"